name: Windows Binary Package

on:
  push:
    branches: [ release ]

jobs:
  build-win-amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9 amd64
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv64
          venv64\Scripts\python -m pip install --upgrade pip wheel setuptools
          venv64\Scripts\python -m pip install -r requirements.txt
          venv64\Scripts\python -m pip install pyinstaller
        shell: cmd
      - name: Make package
        shell: cmd
        run: |
          venv64\Scripts\pyinstaller .\main.spec --onefile
      - name: Upload artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: arknights-mower_cp39_win_amd64
          path: dist/main.exe
